name: Deploy

on:
  repository_dispatch:
  push:
    branches:
      - master
  schedule:
    # Cron syntax cheat sheet: https://devhints.io/cron
    - cron: '0 0 * * 0' # Every Sunday midnight (GMT)

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node_version: '13.x'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build-algolia
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_APP: ${{ secrets.AIRTABLE_BASE_APP }}
          AIRTABLE_BASE_TRANSLATIONS: ${{ secrets.AIRTABLE_BASE_TRANSLATIONS }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
          GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY }}
          GATSBY_FIREBASE_API_KEY: ${{ secrets.GATSBY_FIREBASE_API_KEY }}
          GATSBY_HUBSPOT_BETA_FORM_GUID: ${{ secrets.GATSBY_HUBSPOT_BETA_FORM_GUID }}
          GATSBY_HUBSPOT_PORTAL_ID: ${{ secrets.GATSBY_HUBSPOT_PORTAL_ID }}
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
